config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  get 'users/create'

  post 'users/update'

  resources :sessions, only: [:new, :create]

  get 'main/index'

  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :samples

  root 'main#index'

end

app/models/sample.rb
class Sample < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :email,
  presence: true,
  uniqueness: true,
  format: {
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  }

  # This method associates the attribute ":avatar" with a file attachment
  has_attached_file :avatar, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }

# Validate the attached image is image/jpg, image/png, etc
validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    User.where(id: session[:user_id]).first
  end

  helper_method :current_user

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    if current_user
      @user = current_user
    else
      @user = User.new
    end
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      # redirect_to root_url, notice: 'Logged in!'
      redirect_to root_url, notice: 'Logged in!'
      # if request.xhr?
      #   render '_login-state', layout: false, locals: { logged_in: "true" }
      # end
    else
      # Failed Login
      redirect_to root_url, notice: 'Please Try again'
      # if request.xhr?
      #   # render '_login-state', layout: false, locals: { logged_in: "false" }
      #   render :json => { :errors => "Bad login" }
      # end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @user = current_user
    # binding.pry
    if @user.update(user_params)
      @success = 1
      # binding.pry
      redirect_to root_url

    else
      @success = 0
      # binding.pry
      redirect_to root_url
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.permit(:email, :avatar, :video_url)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Roman Site</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Josefin+Slab' %>
  <!-- <link href='https://fonts.googleapis.com/css?family=Josefin+Slab' rel='stylesheet' type='text/css'> -->
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/_login_form.html.erb
<div id = "login-box" class="blocks cream">
  <button id="login-button-close" type="button" class="close-button transparent">X</button><br>
  <p>
    LOGIN FORM
  </p>

  <%= form_tag sessions_path, id: "login-form" do %>

    <div class="field">
      <%= label_tag :email %><br>
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %><br>
      <%= password_field_tag :password %>
    </div>
    <div class="form-actions">
      <%= submit_tag "Log In" %>
      <button type="button" id="login-cancel-button">CANCEL</button>
    </div>
  <% end %>


  <!-- <div class="login-form">
    <p>USERNAME: <input type="text" name="name" value=""></p>
    <p>PASSWORD: <input type="text" name="name" value=""></p>
  </div>
  <div class="login-buttons">
    <button type="button" id="login-button">LOGIN</button>
    <button type="button" id="password-button">CANCEL</button>
  </div> -->
</div>

app/views/main/_loginform.html.erb
<div id = "login-box" class="blocks cream">
  <button id="login-button-close" type="button" class="close-button transparent">X</button><br>
  <p>
    LOGIN FORM
  </p>

  <%= form_tag sessions_path, remote:true, id: "login-form" do %>

    <div class="field">
      <%= label_tag :email %><br>
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %><br>
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag "Log In" %>
      <button type="button" id="password-button">CANCEL</button>
    </div>
  <% end %>


  <!-- <div class="login-form">
    <p>USERNAME: <input type="text" name="name" value=""></p>
    <p>PASSWORD: <input type="text" name="name" value=""></p>
  </div>
  <div class="login-buttons">
    <button type="button" id="login-button">LOGIN</button>
    <button type="button" id="password-button">CANCEL</button>
  </div> -->
</div>

app/views/main/_set_avatar_form.html.erb
<div id = "set-avatar-box" class="blocks cream">
  <button id="set-avatar-button-close" type="button" class="close-button transparent">X</button><br>
  <p>
    USER PROFILE
  </p>

<%= form_tag users_update_path, method: :post, id: "user-form", authenticity_token: true, multipart: true do %>

  <div class="field">
    <%= label_tag :email %><br>
    <%= text_field_tag :email, @user.email %>
  </div>
  <div class="field">
    <%= label_tag :video_url %><br>
    <%= text_field_tag :video_url, @user.video_url %>
  </div>
  <div class="field">
    <%= label_tag :avatar %>
    <%= file_field_tag :avatar %>
  </div>
  <div class="form-actions">
    <%= submit_tag "Update" %>
    <button type="button" id="update-cancel-button">CANCEL</button>
  </div>
<% end %>

</div>

app/views/main/_uploadform.html.erb
<div id = "upload-box" class="blocks cream">
  <button type="button" class="close-button transparent">X</button><br>
  <p>
    UPLOAD FORM
  </p>
  <div class="upload-form">
    <p>File name: </p>
    <p><input type="file" name="name" value=""></p>
  </div>
  <div class="login-buttons">
    <button type="button" id="login-button">UPLOAD</button>
    <button type="button" id="password-button">CANCEL</button>
  </div>
</div>

app/views/main/index.html.erb
<div id="block-1" class="josefin-font blocks cream">
    <div class="section-top">
      <button type="button" class="close-button transparent">X</button>
      <br>
      <% if current_user %>
        <%= image_tag @user.avatar.url, class: "circular center" %>
      <% else %>
        <%= image_tag "bill-clinton.jpeg", class: "circular center" %>
      <% end %>

      <p class = "block-title">MAXIMUS</p>
      <p>LEGIO HISPANIA</p>
      <% if current_user %>
        <%= button_to "LOG OUT", logout_path, id: "logout-button", method: :get %>
        <button id="profile-button">PROFILE</button>
        <div id="log-in-status">
            You are logged in: <%= current_user.email %>
        </div>
      <% else %>
        <button id="login-button">LOG IN</button>
        <!-- <button id="profile-button">PROFILE</button> -->
      <% end %>

    </div>
    <!-- <input type="button" id="login-button" value="Go to Google" /> -->

    <%# button_tag "LOG IN", type: "button", id: "login-button" %>

    <div class="section-footer light-gray">
      <div>
        <p>LXIII</p>
        <p>ENEMIES</p>
      </div>
      <div>
        <p>VII</p>
        <p>CONQUERED</p>
      </div>
      <div>
        <p>III</p>
        <p>RANK</p>
      </div>
    </div>

</div>
<div id="image-block" class="image blocks">
  <button type="button" class="close-button transparent">X</button>
    <% if current_user %>
      <iframe width="338" height="248"
        src="<%= current_user.video_url %>">
      </iframe>
    <% else %>
      <%= image_tag "gladiator.jpeg" %>
    <% end %>
</div>
<div id="big-text-block" class="big-text blocks brown">
  <p class = "josefin-font big-text">
    ACDEFHGIJMNLTRSUVQXWYOP
  </p>
  <img src="https://placehold.it/50x50" class="center" alt="#" />
</div>


<div id="legio-hispania" class="blocks cream">
  <button type="button" class="close-button transparent">X</button><br><br>
  <img src="https://placehold.it/50x50" class="center" alt="#" />
  <p class="block-title">
    LEGIO HISPANIA
  </p>
  <p>
    <span><img src="https://placehold.it/80x15" alt="#" /></span> XV <span><img src="https://placehold.it/80x15" alt="#" /></span>
  </p>
  <br>
  <div class="legios orange">
    <p>COHORTS<span>XII</span></p>
  </div>
  <div class="legios light-brown">
    <p>LEGIONAIRES<span>MMDL</span></p>
  </div>
  <div class="legios brown">
    <p>EQUITES<span>LXIII</span></p>
  </div><br><br>
  <div class="rings">
    <span>XII</span><span>XV</span><span>III</span>
  </div>
</div>
<div id="map-with-charts" class="blocks cream">
  <button type="button" class="close-button transparent">X</button>
  <!-- <img src="https://placehold.it/340x240" alt="#" /> -->
  <%= image_tag "brown-map.jpeg" %>
  <div class="secondary-section">
    <div class="warfare-blocks">
      <p>WARFARE STATS<span><img src="https://placehold.it/140x35" alt="#" /></span></p>
    </div>
    <div class="warfare-blocks">
      <p>SLAVES CONQUERED<span><img src="https://placehold.it/140x35" alt="#" /></span></p>
    </div>
    <div class="warfare-blocks">
      <p>WARFARE FORMATION<span><img src="https://placehold.it/140x35" alt="#" /></span></p>
    </div>
  </div>
</div>

<div id="surrender" class="blocks cream">
  <button type="button" class="close-button transparent">X</button><br>
  <img src="https://placehold.it/50x50" class="center" alt="#" />
  <p class="block-title">
    SURRENDER
  </p>
  <p>
    ANNIHILATED <span>BY</span> LEGIO HISPANIA
  </p>
  <img class = "circular center" src="https://placehold.it/50x50" alt="#" />
</div>

<%= render 'login_form' %>
<%= render 'set_avatar_form' %>

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Samples</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= sample.name %></td>
        <td><%= link_to 'Show', sample %></td>
        <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
        <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample', new_sample_path %>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sample.name %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/update.html.erb
<% if @success == 1 %>
  <span>Profile changed</span>
<% else %>
  <span>Profile not changed</span>
<% end %>